accounts/urls.py
from django.urls import path

from accounts.views import LoginView, LogoutView, VendeeSignUpView, VendorSignUpView, ResetPasswordView, \
    ResetPasswordConfirmView
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [

    path('login/', LoginView.as_view(), name='login'),

    path('logout/', LogoutView.as_view(), name='logout'),

    path('password_reset/', ResetPasswordView.as_view(), name='password_reset'),

    # path('password_reset/',
    #      auth_views.PasswordResetView.as_view(template_name='authentication/password/password_reset.html'),
    #      name='password_reset_done'),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='authentication/password/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', ResetPasswordConfirmView.as_view(), name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='authentication/password/password_reset_complete'
                                                                    '.html'),
         name='password_reset_complete'),

    path('vendor/signup/', VendorSignUpView.as_view(), name='vendor_signup'),

    path('vendee/signup/', VendeeSignUpView.as_view(), name='vendee_signup'),

]

# accounts / login / [name = 'login']
# accounts / logout / [name = 'logout']
# accounts / password_change / [name = 'password_change']
# accounts / password_change / done / [name = 'password_change_done']
# accounts / password_reset / [name = 'password_reset']
# accounts / password_reset / done / [name = 'password_reset_done']
# accounts / reset / < uidb64 > / < token > / [name = 'password_reset_confirm']
# accounts / reset / done / [name = 'password_reset_complete']

vendees/urls.py
from django.urls import path

from vendees.views import VendeeHomeView

app_name = 'vendee'

urlpatterns = [

    path('dashboard/', VendeeHomeView.as_view(), name='vendee-home'),

]

accounts/models.py
import datetime

from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.forms import model_to_dict
from django.urls import reverse
from django.utils.text import slugify
from django_countries.fields import CountryField, Country
from phonenumber_field.modelfields import PhoneNumberField
from phonenumber_field.phonenumber import PhoneNumber
from django.db.models import Value
from versatileimagefield.fields import VersatileImageField

from . import Gender
from .validators import validate_possible_number

# Create your models here.

# Manager to manage and create users.
from malls import MallTypeKind


class MobileNumberField(PhoneNumberField):
    default_validators = [validate_possible_number]


class AddressQueryset(models.QuerySet):

    def annotate_default(self, user):
        # Set default shipping/billing address pk to None
        # if default shipping/billing address doesn't exist
        default_shipping_address_pk, default_billing_address_pk = None, None
        if user.default_shipping_address:
            default_shipping_address_pk = user.default_shipping_address.pk
        if user.default_billing_address:
            default_billing_address_pk = user.default_billing_address.pk

        return user.addresses.annotate(
            user_default_shipping_address_pk=Value(
                default_shipping_address_pk, models.IntegerField()
            ),
            user_default_billing_address_pk=Value(
                default_billing_address_pk, models.IntegerField()
            ),
        )


class Address(models.Model):
    first_name = models.CharField(max_length=256, blank=True)
    last_name = models.CharField(max_length=256, blank=True)
    company_name = models.CharField(max_length=256, blank=True)
    street_address_1 = models.CharField(max_length=256, blank=True)
    street_address_2 = models.CharField(max_length=256, blank=True)
    city = models.CharField(max_length=256, blank=True)
    city_area = models.CharField(max_length=128, blank=True)
    postal_code = models.CharField(max_length=20, blank=True)
    country = CountryField()
    country_area = models.CharField(max_length=128, blank=True)
    phone = MobileNumberField(blank=True, default="", db_index=True)

    objects = models.Manager.from_queryset(AddressQueryset)()

    class Meta:
        ordering = ("pk",)

    @property
    def full_name(self):
        return "%s %s" % (self.first_name, self.last_name)

    def __str__(self):
        if self.company_name:
            return "%s - %s" % (self.company_name, self.full_name)
        return self.full_name

    def __eq__(self, other):
        if not isinstance(other, Address):
            return False
        return self.as_data() == other.as_data()

    __hash__ = models.Model.__hash__

    def as_data(self):
        """Return the address as a dict suitable for passing as kwargs.

        Result does not contain the primary key or an associated user.
        """
        data = model_to_dict(self, exclude=["id", "user"])
        if isinstance(data["country"], Country):
            data["country"] = data["country"].code
        if isinstance(data["phone"], PhoneNumber):
            data["phone"] = data["phone"].as_e164
        return data

    def get_copy(self):
        """Return a new instance of the same address."""
        return Address.objects.create(**self.as_data())


class AccountManager(BaseUserManager):
    use_in_migrations = True

    def create_user(self, email, first_name, last_name, password=None, is_active=True, is_superuser=False,
                    is_staff=False, is_admin=False,
                    is_vendee=False, is_vendor=False, is_dispatcher=False):
        if not email:
            raise ValueError("Sorry!, an email address is needed. Please provide one.")
        if not password:
            raise ValueError("Sorry!, an alphanumeric password must be  provided.")
        user = self.model(email=self.normalize_email(email), first_name=first_name, last_name=last_name)
        user.set_password(password)
        user.superuser = is_superuser
        user.staff = is_staff
        user.admin = is_admin
        user.active = is_active
        user.save(using=self.db)
        return user

    def create_staff(self, email, first_name, last_name, password=None):
        user = self.create_user(email, first_name=first_name, last_name=last_name, password=password, is_staff=True)
        return user

    def create_superuser(self, email, first_name, last_name, password=None):
        user = self.create_user(email, first_name=first_name, last_name=last_name, password=password, is_superuser=True,
                                is_staff=True, is_vendor=True, is_vendee=True, is_dispatcher=True, is_admin=True)
        return user


# Model defining the end usersÒ
class WebUser(PermissionsMixin, AbstractBaseUser):
    email = models.EmailField(unique=True, verbose_name='Email address')
    first_name = models.CharField(max_length=256, blank=True)
    last_name = models.CharField(max_length=256, blank=True)
    addresses = models.ManyToManyField(Address, blank=True, related_name='user_addresses')
    avatar = VersatileImageField(upload_to="user-avatars", blank=True, null=True)
    birth_date = models.DateField(verbose_name='Birth date', blank=True, null=True, default=datetime.date.today)
    gender = models.CharField(choices=Gender.CHOICES, max_length=36, default="Male", null=True, blank=True)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    is_vendee = models.BooleanField(default=False, verbose_name="Vendee Account")
    is_vendor = models.BooleanField(default=False, verbose_name='Vendor Account')
    is_dispatcher = models.BooleanField(default=False, verbose_name="Dispatcher Account")
    is_active = models.BooleanField(default=True, verbose_name="Active Account")
    last_login = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True, db_index=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = AccountManager()

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"

    def __str__(self):
        return self.email

    def get_full_name(self):
        if self.first_name and self.last_name:
            return F"{self.first_name} {self.last_name}"
        return self.email

    def get_short_name(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        if self.is_admin:
            return True
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    @property
    def vendee(self):
        return self.is_vendee

    @property
    def vendor(self):
        return self.is_vendor

    @property
    def dispatcher(self):
        return self.is_dispatcher

    def check_active(self):
        if self.is_active:
            return "Your account is Active!"
        else:
            return "Your account is not Activated!"


class Vendor(models.Model):
    user = models.OneToOneField(WebUser, on_delete=models.CASCADE, primary_key=True)
    business_name = models.CharField(max_length=256)
    business_type = models.CharField(max_length=32, choices=MallTypeKind.CHOICES, default='SUPERMARKET')

    class Meta:
        verbose_name_plural = 'Vendors'

    def __str__(self):
        if self.user.email:
            return self.user.email
        return self.business_name

    def get_absolute_url(self):
        kwargs = {"pk": self.pk}
        return reverse("vendors:vendor-detail", kwargs=kwargs)

    # def generate_slug(self):
    #     max_length = 256
    #     value = self.business_name
    #     slug_candidate = slug_original = slugify(value, allow_unicode=True)[:max_length]
    #     for i in itertools.count(1):
    #         if not Vendor.objects.filter(slug=slug_candidate).exists():
    #             break
    #         id_length = len(str(i)) + 1
    #         new_slug_text_part_length = len(slug_original) - id_length
    #         original_slug_with_id_length = len(slug_original) + id_length
    #
    #         candidate_slug_part = slug_original[
    #                               :new_slug_text_part_length] if original_slug_with_id_length > max_length else slug_original
    #         slug_candidate = "{}-{}".format(candidate_slug_part, i)
    #
    #     self.slug = slug_candidate
    #
    # def slug_length(self):
    #     return len(self.slug)
    #
    # def get_absolute_url(self):
    #     return reverse("vendors:vendor-detail", args=[str(self.slug)])
    #
    # def save(self, *args, **kwargs):
    #     if not self.pk:
    #         self.generate_slug()
    #
    #     super().save(*args, **kwargs)
    #
    #     pass


class Vendee(models.Model):
    user = models.OneToOneField(WebUser, on_delete=models.CASCADE, primary_key=True)
    default_shipping_address = models.ForeignKey(
        Address, related_name="+", null=True, blank=True, on_delete=models.SET_NULL)
    default_billing_address = models.ForeignKey(
        Address, related_name="+", null=True, blank=True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name_plural = 'Vendee'

    def __str__(self):
        if self.user.email:
            return self.user.email
        return self.user.first_name

    pass

accounts/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model, authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.views import PasswordResetView, PasswordResetCompleteView, PasswordResetConfirmView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import FormView, TemplateView, CreateView

from accounts.forms import LoginForm, VendeeSignUpForm, VendorSignUpForm, ResetPasswordForm

User = get_user_model()


# Account authentication views


# View for logging in members

class LoginView(FormView):
    content = {'form': LoginForm}

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        content = {}
        if request.user.is_authenticated and request.user.is_vendor:
            return redirect(reverse('vendors:vendors-home'))
        elif request.user.is_authenticated and request.user.is_vendee:
            return redirect(reverse('vendee:vendee-home'))
        else:
            pass

        content['form'] = LoginForm
        return render(request, 'authentication/login.html', content)

    def post(self, request, *args, **kwargs):
        content = {}
        email = request.POST['email']
        password = request.POST['password']

        try:
            users = User.objects.filter(email=email)
            user = authenticate(request, email=users.first().email, password=password)
            login(request, user)
            if request.user.is_vendee:
                return redirect(reverse('vendee:vendee-home'))
            elif request.user.is_vendor:
                return redirect(reverse('vendors:vendor-home'))
            else:
                pass

        except Exception as e:
            content = {'form': LoginForm, 'error': 'Unable to login with the provided credential' + e}
            return render(request, 'authentication/login.html', content)


# View to log out members
class LogoutView(FormView):
    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect('/')


class VendorSignUpView(CreateView):
    model = User
    form_class = VendorSignUpForm
    template_name = 'authentication/vendor_signup.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user.is_vendor:
            return redirect(reverse('vendors:vendors-home'))
        content = {'form': VendorSignUpForm}
        return render(request, 'authentication/vendor_signup.html', content)

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'vendor'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        vendor = user.vendor
        user.vendor.business_name = form.cleaned_data.get('business_name')
        user.vendor.business_type = form.cleaned_data.get('business_type')
        vendor.business_name = user.vendor.business_name
        vendor.business_type = user.vendor.business_type
        vendor.save()
        login(self.request, user)
        form.send_mail()
        messages.success(self.request,
                         f" Hello {user.vendor.business_name}! Your vendor account with email address {user.email} "
                         f"has been created."
                         )
        return redirect('vendors:vendors-home')


# View for registering customers
class VendeeSignUpView(CreateView):
    model = User
    form_class = VendeeSignUpForm
    template_name = 'authentication/vendee_signup.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user.is_vendee:
            return redirect(reverse('vendee:vendee-home'))
        content = {'form': VendeeSignUpForm}
        return render(request, 'authentication/vendee_signup.html', content)

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'vendee'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        vendee = user.vendee
        vendee.save()
        login(self.request, user)
        form.send_email()
        messages.success(self.request,
                         f" Hello {user.first_name}! Your customer account with email address {user.email} "
                         f"has been created."
                         )
        return redirect('vendee:vendee-home')

    pass


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    form_class = ResetPasswordForm
    template_name = 'authentication/password/password_reset.html'
    email_template_name = 'authentication/password/password_reset_email.html'
    subject_template_name = 'authentication/password/password_reset_subject.txt'
    success_url = reverse_lazy("accounts:password_reset_done")
    pass


class ResetPasswordConfirmView(PasswordResetConfirmView):
    template_name = 'authentication/password/password_reset_confirm.html'
    success_url = reverse_lazy("accounts:password_reset_complete")

accounts/templates/authentication/vendee_signup.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Customer Registration {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Section -->
    <section class="min-vh-100 d-flex align-items-center section-image overlay-soft-dark" data-background="/static/assets/img/pages/customer-bg.jpg">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 d-flex align-items-center justify-content-center">
                    <div class="signin-inner my-4 my-lg-0 bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">

                        <div class="text-center text-md-center mb-4 mt-md-0">
                            <h2 class="mb-0 h3">CUSTOMER REGISTRATION</h2>
                            <p class="text-center">
                                {% if msg %}
                                    {{ msg | safe }}
                                {% else %}
                                    Add your credentials
                                {% endif %}
                            </p>
                        </div>

                        <form method="post" action="" class="mt-4">

                            {% csrf_token %}

                            <!-- Form -->
                            <div class="form-group mb-4">
                                <label for="id_email">Email Address</label>
                                <div class="input-group">
                                    <span class="input-group-text" id="basic-addon3"><span class="fas fa-envelope"></span></span>
                                    {{ form.email }}
                                </div>
                                <span class="text-error">{{ form.email.errors }}</span>
                            </div>
                            <!-- End of Form -->

                             <!-- Form -->
                            <div class="form-group mb-4">
                                <label for="id_first_name">First Name</label>
                                <div class="input-group">
                                    <span class="input-group-text" id="basic-addon3"><span class="fas fa-envelope"></span></span>
                                    {{ form.first_name }}
                                </div>
                                <span class="text-error">{{ form.first_name.errors }}</span>
                            </div>
                            <!-- End of Form -->

                             <!-- Form -->
                            <div class="form-group mb-4">
                                <label for="id_last_name">Last Name</label>
                                <div class="input-group">
                                    <span class="input-group-text" id="basic-addon3"><span class="fas fa-envelope"></span></span>
                                    {{ form.last_name }}
                                </div>
                                <span class="text-error">{{ form.last_name.errors }}</span>
                            </div>
                            <!-- End of Form -->

                            <div class="form-group">
                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="id_password1">Password</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon4"><span class="fas fa-unlock-alt"></span></span>
                                        {{ form.password1 }}
                                    </div>
                                    <span class="text-error">{{ form.password1.errors }}</span>
                                </div>
                                <!-- End of Form -->

                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="id_password2">Password Confirmation</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon4"><span class="fas fa-unlock-alt"></span></span>
                                        {{ form.password2 }}
                                    </div>
                                    <span class="text-error">{{ form.password2.errors }}</span>
                                </div>
                                <!-- End of Form -->
                            </div>
                            <div class="d-grid">
                                <button type="submit" name="register" class="btn btn-block btn-primary">REGISTER</button>
                            </div>
                        </form>
                        <div class="d-flex justify-content-center align-items-center mt-4">
                            <span class="font-weight-normal">
                                Already registered?
                                <a href="{% url 'accounts:login' %}" class="font-weight-bold">Sign IN</a>
                            </span>
                        </div>
                    </div>
                </div>

                <div class="col-12 d-flex align-items-center justify-content-center">
                    <br />
                </div>
                <div class="col-12 d-flex align-items-center justify-content-center">
                    <br />
                    <span class="text-white font-small">
                        &copy; <a target="_blank" rel="noopener noreferrer" href="https://uloahia.ng">ULOAHIA</a>
                        - made with love by <a target="_blank" rel="noopener noreferrer" href="https://uloahia.ng">ULOAHIA LIMITED</a>.
                    </span>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

accounts/templates/authentication/vendor_signup.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Vendor Registration {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- Section -->
    <section class="min-vh-100 d-flex align-items-center section-image overlay-soft-dark" data-background="/static/assets/img/pages/vendor-bg.jpg">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 d-flex align-items-center justify-content-center">
                    <div class="signin-inner my-4 my-lg-0 bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">

                        <div class="text-center text-md-center mb-4 mt-md-0">
                            <h2 class="mb-0 h3">VENDOR REGISTRATION</h2>
                            <p class="text-center">
                                {% if msg %}
                                    {{ msg | safe }}
                                {% else %}
                                    Add your credentials
                                {% endif %}
                            </p>
                        </div>

                        <form method="post" action="" class="mt-4">

                            {% csrf_token %}

                            <!-- Form -->
                            <div class="form-group mb-4">
                                <label for="id_email">Email Address</label>
                                <div class="input-group">
                                    <span class="input-group-text" id="basic-addon3"><span class="fas fa-envelope"></span></span>
                                    {{ form.email }}
                                </div>
                                <span class="text-error">{{ form.email.errors }}</span>
                            </div>
                            <!-- End of Form -->

                             <!-- Form -->
                            <div class="form-group mb-4">
                                <label for="id_first_name">First Name</label>
                                <div class="input-group">
                                    <span class="input-group-text" id="basic-addon3"><span class="fas fa-user"></span></span>
                                    {{ form.first_name }}
                                </div>
                                <span class="text-error">{{ form.first_name.errors }}</span>
                            </div>
                            <!-- End of Form -->

                             <!-- Form -->
                            <div class="form-group mb-4">
                                <label for="id_last_name">Last Name</label>
                                <div class="input-group">
                                    <span class="input-group-text" id="basic-addon3"><span class="fas fa-user"></span></span>
                                    {{ form.last_name }}
                                </div>
                                <span class="text-error">{{ form.last_name.errors }}</span>
                            </div>
                            <!-- End of Form -->

                               <!-- Form -->
                            <div class="form-group mb-4">
                                <label for="id_business_name">Business Name</label>
                                <div class="input-group">
                                    <span class="input-group-text" id="basic-addon3"><span class="fas fa-store"></span></span>
                                    {{ form.business_name }}
                                </div>
                                <span class="text-error">{{ form.business_name.errors }}</span>
                            </div>
                            <!-- End of Form -->

                               <!-- Form -->
                            <div class="form-group mb-4">
                                <label for="id_business_type">Business Type</label>
                                <div class="input-group">
                                    <span class="input-group-text" id="basic-addon3"><span class="fas fa-store"></span></span>
                                    {{ form.business_type }}
                                </div>
                                <span class="text-error">{{ form.business_type.errors }}</span>
                            </div>
                            <!-- End of Form -->

                            <div class="form-group">
                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="id_password1">Password</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon4"><span class="fas fa-unlock-alt"></span></span>
                                        {{ form.password1 }}
                                    </div>
                                    <span class="text-error">{{ form.password1.errors }}</span>
                                </div>
                                <!-- End of Form -->

                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <label for="id_password2">Password Confirmation</label>
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon4"><span class="fas fa-unlock-alt"></span></span>
                                        {{ form.password2 }}
                                    </div>
                                    <span class="text-error">{{ form.password2.errors }}</span>
                                </div>
                                <!-- End of Form -->
                            </div>
                            <div class="d-grid">
                                <button type="submit" name="register" class="btn btn-block btn-primary">REGISTER</button>
                            </div>
                        </form>
                        <div class="d-flex justify-content-center align-items-center mt-4">
                            <span class="font-weight-normal">
                                Already registered?
                                <a href="{% url 'accounts:login' %}" class="font-weight-bold">LOG IN Here</a>
                            </span>
                        </div>
                    </div>
                </div>

                <div class="col-12 d-flex align-items-center justify-content-center">
                    <br />
                </div>
                <div class="col-12 d-flex align-items-center justify-content-center">
                    <br />
                    <span class="text-white font-small">
                        &copy; <a target="_blank" rel="noopener noreferrer" href="https://uloahia.ng">ULOAHIA</a>
                        - made with love by <a target="_blank" rel="noopener noreferrer" href="https://uloahia.ng">ULOAHIA LIMITED</a>.
                    </span>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}