accounts/urls.py
from django.urls import path

from accounts.views import LoginView, LogoutView, VendeeSignUpView, VendorSignUpView, ResetPasswordView, \
    ResetPasswordConfirmView
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns = [

    path('login/', LoginView.as_view(), name='login'),

    path('logout/', LogoutView.as_view(), name='logout'),

    path('password_reset/', ResetPasswordView.as_view(), name='password_reset'),

    # path('password_reset/',
    #      auth_views.PasswordResetView.as_view(template_name='authentication/password/password_reset.html'),
    #      name='password_reset_done'),

    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='authentication/password/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', ResetPasswordConfirmView.as_view(), name='password_reset_confirm'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='authentication/password/password_reset_complete'
                                                                    '.html'),
         name='password_reset_complete'),

    path('vendor/signup/', VendorSignUpView.as_view(), name='vendor_signup'),

    path('vendee/signup/', VendeeSignUpView.as_view(), name='vendee_signup'),

]

# accounts / login / [name = 'login']
# accounts / logout / [name = 'logout']
# accounts / password_change / [name = 'password_change']
# accounts / password_change / done / [name = 'password_change_done']
# accounts / password_reset / [name = 'password_reset']
# accounts / password_reset / done / [name = 'password_reset_done']
# accounts / reset / < uidb64 > / < token > / [name = 'password_reset_confirm']
# accounts / reset / done / [name = 'password_reset_complete']

vendees/urls.py
from django.urls import path

from vendees.views import VendeeHomeView

app_name = 'vendee'

urlpatterns = [

    path('dashboard/', VendeeHomeView.as_view(), name='vendee-home'),

]

vendors/urls.py
from django.urls import path

from vendors.views import VendorsHomeView, VendorUpdateView, VendorDetailView, VendorCatalogHomeView

app_name = 'vendors'
urlpatterns = [

    path('dashboard/', VendorsHomeView.as_view(), name='vendors-home'),

    path('catalog/', VendorCatalogHomeView.as_view(), name='vendors-catalog'),

    path('<int:pk>/<uuid>/update/', VendorUpdateView.as_view(), name='vendors-update'),

    path('detail/', VendorDetailView.as_view(), name='vendors-detail')

]

templates/includes/footer.html
<!-- Small Footer -->
<footer class="footer section section-sm bg-white text-gray">
    <div class="container">
        <div class="row align-items-md-center">
            <div class="col-md-4 mb-4 mb-md-0">
                <div class="d-flex align-items-center">
                    <!-- Logo -->
                    <a class="footer-brand brand-sm me-3" href="/">
                        <img src="/static/assets/img/brand/uloahia-web_logo.svg " alt="ULOAHIA logo">
                    </a>
                    <!-- End Logo -->
                    <p class="small mb-0">© 2022, ULOAHIA LIMITED - RC1819508.<br>All rights reserved.</p>
                </div>
            </div>

            <div class="col-sm-6 col-md-4 mb-4 mb-sm-0">
                <!-- List -->
                <ul class="list-inline list-group-flush list-group-borderless text-md-center mb-0">
                    <li class="list-inline-item px-0 px-sm-2">
                        <a class="text-gray" href="#">About</a>
                    </li>
                    <li class="list-inline-item px-0 px-sm-2">
                        <a class="text-gray" href="#">Terms</a>
                    </li>
                    <li class="list-inline-item px-0 px-sm-2">
                        <a class="text-gray" href="#">Contact</a>
                    </li>
                </ul>
                <!-- End List -->
            </div>

            <div class="col-sm-6 col-md-4">
                <!-- Social Networks -->
                <ul class="list-inline text-sm-right mb-0">
                    <li class="list-inline-item">
                        <a class="icon icon-xs icon-twitter me-3">
                            <span class="fab fa-twitter"></span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="icon icon-xs icon-facebook me-3">
                            <span class="fab fa-facebook-f"></span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="icon icon-xs icon-github me-3">
                            <span class="fab fa-github"></span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="icon icon-xs icon-dribbble me-3">
                            <span class="fab fa-dribbble"></span>
                        </a>
                    </li>
                </ul>
                <!-- End Social Networks -->
            </div>
        </div>
    </div>
</footer>

templates/includes/messages.html
{% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
        <span class="fas fa-bullhorn me-1"></span>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        {{ message }}
    </div>
{% endfor %}

templates/includes/preloader.html
<div class="preloader bg-dark flex-column justify-content-center align-items-center">
    <svg id="loader-logo" xmlns="http://www.w3.org/2000/svg" width="50" height="50" viewBox="0 0 64 78.4">
        <path fill="#fff" d="M10,0h1.2V11.2H0V10A10,10,0,0,1,10,0Z"/>
        <rect fill="none" stroke="#fff" stroke-width="11.2" x="40" y="17.6" width="0" height="25.6"/>
        <rect fill="none" stroke="#fff" stroke-opacity="0.4" stroke-width="11.2" x="23" y="35.2" width="0" height="25.6"/>
        <path fill="#fff" d="M52.8,35.2H64V53.8a7,7,0,0,1-7,7H52.8V35.2Z"/>
        <rect fill="none" stroke="#fff" stroke-width="11.2" x="6" y="52.8" width="0" height="25.6"/>
        <path fill="#fff" d="M52.8,0H57a7,7,0,0,1,7,7h0v4.2H52.8V0Z"/>
        <rect fill="none" stroke="#fff" stroke-opacity="0.4" stroke-width="11.2" x="57.8" y="17.6" width="0" height="11.2"/>
        <rect fill="none" stroke="#fff" stroke-width="11.2" x="6" y="35.2" width="0" height="11.2"/>
        <rect fill="none" stroke="#fff" stroke-width="11.2" x="40.2" y="49.6" width="0" height="11.2"/>
        <path fill="#fff" d="M17.6,67.2H28.8v1.2a10,10,0,0,1-10,10H17.6V67.2Z"/>
        <rect fill="none" stroke="#fff" stroke-opacity="0.4" stroke-width="28.8" x="31.6" width="0" height="11.2"/>
        <rect fill="none" stroke="#fff" x="14" stroke-width="28.8" y="17.6" width="0" height="11.2"/>
    </svg>
</div>

templates/includes/scripts.html
<!-- Core -->
<script src="/static/assets/vendor/@popperjs/core/dist/umd/popper.min.js"></script>
<script src="/static/assets/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="/static/assets/vendor/headroom.js/dist/headroom.min.js"></script>

<!-- Vendor JS -->
<script src="/static/assets/vendor/onscreen/dist/on-screen.umd.min.js"></script>
<script src="/static/assets/vendor/nouislider/distribute/nouislider.min.js"></script>
<script src="/static/assets/vendor/jarallax/dist/jarallax.min.js"></script>
<script src="/static/assets/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js"></script>
<script src="/static/assets/vendor/vivus/dist/vivus.min.js"></script>
<script src="/static/assets/vendor/chartist/dist/chartist.min.js"></script>
<script src="/static/assets/vendor/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js"></script>
<script src="/static/assets/vendor/@glidejs/glide/dist/glide.min.js"></script>
<script src="/static/assets/vendor/countup.js/dist/countUp.umd.js"></script>
<script src="/static/assets/vendor/vanillajs-datepicker/dist/js/datepicker.min.js"></script>

<script async defer src="https://buttons.github.io/buttons.js"></script>

<!-- pixel JS -->
<script src="/static/assets/js/pixel.js"></script>

templates/includes/vendorMenu.html
<div class="col-12 col-lg-4 mb-3 mb-lg-0">
    <!-- Navigation -->
    <div class="card border-gray-300 p-2">
        <div class="card-header bg-white border-0 text-center d-flex flex-row flex-lg-column align-items-center justify-content-center px-1 px-lg-4">
            <div class="profile-thumbnail dashboard-avatar mx-lg-auto me-3">
                <img src="{{ user.avatar.thumbnail__200x200 }}"
                     class="card-img-top rounded-circle border-white" alt="Bonnie Green Portrait">
            </div>
            <span class="h5 my-0 my-lg-3 me-3 me-lg-0">Hi, {{ user.vendor.business_name }}!</span>
            <a href="{% url 'accounts:logout' %}" class="btn btn-gray-300 btn-xs"><span
                    class="me-2"><span
                    class="fas fa-sign-out-alt"></span></span>Sign Out</a>
        </div>
        <div class="card-body p-2 d-none d-lg-block">
            <ul class="list-group dashboard-menu list-group-sm">
                <a href="{% url 'vendors:vendors-home' %}"
                   class="d-flex list-group-item border-0 list-group-item-action  active ">Overview
                    <span class="icon icon-xs ms-auto"><span class="fas fa-briefcase"></span></span>
                </a>
                <a href="{% url 'vendors:vendors-catalog' %}"
                   class="d-flex list-group-item border-0 list-group-item-action ">Catalog<span
                        class="icon icon-xs ms-auto"><span class="fas fa-shopping-bag"></span></span>
                </a>
                <a href="/dashboard-my-items.html"
                   class="d-flex list-group-item border-0 list-group-item-action ">Orders<span
                        class="icon icon-xs ms-auto"><span class="fas fa-shopping-cart"></span></span>
                </a>
                <a href="/dashboard-security.html"
                   class="d-flex list-group-item border-0 list-group-item-action ">Customers<span
                        class="icon icon-xs ms-auto"><span class="fas fa-user"></span></span>
                </a>
                <a href="/dashboard-billing.html"
                   class="d-flex list-group-item border-0 list-group-item-action ">Discounts<span
                        class="icon icon-xs ms-auto"><span class="fas fa-wallet"></span></span>
                </a>
                <a href="{% url 'vendors:vendors-update' user.pk uuid %}"
                   class="d-flex list-group-item border-0 list-group-item-action  border-0">Settings<span
                        class="icon icon-xs ms-auto"><span class="fas fa-tools"></span></span>
                </a>
            </ul>
        </div>
    </div>
</div>