vendees/urls.py
from django.urls import path

from vendees.views import VendeeHomeView

app_name = 'vendee'

urlpatterns = [

    path('dashboard/', VendeeHomeView.as_view(), name='vendee-home'),

]

vendors/urls.py
from django.urls import path

from vendors.views import VendorsHomeView, VendorUpdateView, VendorDetailView, VendorCatalogHomeView

app_name = 'vendors'
urlpatterns = [

    path('dashboard/', VendorsHomeView.as_view(), name='vendors-home'),

    path('catalog/', VendorCatalogHomeView.as_view(), name='vendors-catalog'),

    path('<int:pk>/<uuid>/update/', VendorUpdateView.as_view(), name='vendors-update'),

    path('detail/', VendorDetailView.as_view(), name='vendors-detail')

]

accounts/models.py
import datetime

from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.forms import model_to_dict
from django.urls import reverse
from django.utils.text import slugify
from django_countries.fields import CountryField, Country
from phonenumber_field.modelfields import PhoneNumberField
from phonenumber_field.phonenumber import PhoneNumber
from django.db.models import Value
from versatileimagefield.fields import VersatileImageField

from . import Gender
from .validators import validate_possible_number

# Create your models here.

# Manager to manage and create users.
from malls import MallTypeKind


class MobileNumberField(PhoneNumberField):
    default_validators = [validate_possible_number]


class AddressQueryset(models.QuerySet):

    def annotate_default(self, user):
        # Set default shipping/billing address pk to None
        # if default shipping/billing address doesn't exist
        default_shipping_address_pk, default_billing_address_pk = None, None
        if user.default_shipping_address:
            default_shipping_address_pk = user.default_shipping_address.pk
        if user.default_billing_address:
            default_billing_address_pk = user.default_billing_address.pk

        return user.addresses.annotate(
            user_default_shipping_address_pk=Value(
                default_shipping_address_pk, models.IntegerField()
            ),
            user_default_billing_address_pk=Value(
                default_billing_address_pk, models.IntegerField()
            ),
        )


class Address(models.Model):
    first_name = models.CharField(max_length=256, blank=True)
    last_name = models.CharField(max_length=256, blank=True)
    company_name = models.CharField(max_length=256, blank=True)
    street_address_1 = models.CharField(max_length=256, blank=True)
    street_address_2 = models.CharField(max_length=256, blank=True)
    city = models.CharField(max_length=256, blank=True)
    city_area = models.CharField(max_length=128, blank=True)
    postal_code = models.CharField(max_length=20, blank=True)
    country = CountryField()
    country_area = models.CharField(max_length=128, blank=True)
    phone = MobileNumberField(blank=True, default="", db_index=True)

    objects = models.Manager.from_queryset(AddressQueryset)()

    class Meta:
        ordering = ("pk",)

    @property
    def full_name(self):
        return "%s %s" % (self.first_name, self.last_name)

    def __str__(self):
        if self.company_name:
            return "%s - %s" % (self.company_name, self.full_name)
        return self.full_name

    def __eq__(self, other):
        if not isinstance(other, Address):
            return False
        return self.as_data() == other.as_data()

    __hash__ = models.Model.__hash__

    def as_data(self):
        """Return the address as a dict suitable for passing as kwargs.

        Result does not contain the primary key or an associated user.
        """
        data = model_to_dict(self, exclude=["id", "user"])
        if isinstance(data["country"], Country):
            data["country"] = data["country"].code
        if isinstance(data["phone"], PhoneNumber):
            data["phone"] = data["phone"].as_e164
        return data

    def get_copy(self):
        """Return a new instance of the same address."""
        return Address.objects.create(**self.as_data())


class AccountManager(BaseUserManager):
    use_in_migrations = True

    def create_user(self, email, first_name, last_name, password=None, is_active=True, is_superuser=False,
                    is_staff=False, is_admin=False,
                    is_vendee=False, is_vendor=False, is_dispatcher=False):
        if not email:
            raise ValueError("Sorry!, an email address is needed. Please provide one.")
        if not password:
            raise ValueError("Sorry!, an alphanumeric password must be  provided.")
        user = self.model(email=self.normalize_email(email), first_name=first_name, last_name=last_name)
        user.set_password(password)
        user.superuser = is_superuser
        user.staff = is_staff
        user.admin = is_admin
        user.active = is_active
        user.save(using=self.db)
        return user

    def create_staff(self, email, first_name, last_name, password=None):
        user = self.create_user(email, first_name=first_name, last_name=last_name, password=password, is_staff=True)
        return user

    def create_superuser(self, email, first_name, last_name, password=None):
        user = self.create_user(email, first_name=first_name, last_name=last_name, password=password, is_superuser=True,
                                is_staff=True, is_vendor=True, is_vendee=True, is_dispatcher=True, is_admin=True)
        return user


# Model defining the end usersÒ
class WebUser(PermissionsMixin, AbstractBaseUser):
    email = models.EmailField(unique=True, verbose_name='Email address')
    first_name = models.CharField(max_length=256, blank=True)
    last_name = models.CharField(max_length=256, blank=True)
    addresses = models.ManyToManyField(Address, blank=True, related_name='user_addresses')
    avatar = VersatileImageField(upload_to="user-avatars", blank=True, null=True)
    birth_date = models.DateField(verbose_name='Birth date', blank=True, null=True, default=datetime.date.today)
    gender = models.CharField(choices=Gender.CHOICES, max_length=36, default="Male", null=True, blank=True)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    is_vendee = models.BooleanField(default=False, verbose_name="Vendee Account")
    is_vendor = models.BooleanField(default=False, verbose_name='Vendor Account')
    is_dispatcher = models.BooleanField(default=False, verbose_name="Dispatcher Account")
    is_active = models.BooleanField(default=True, verbose_name="Active Account")
    last_login = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True, db_index=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = AccountManager()

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"

    def __str__(self):
        return self.email

    def get_full_name(self):
        if self.first_name and self.last_name:
            return F"{self.first_name} {self.last_name}"
        return self.email

    def get_short_name(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        if self.is_admin:
            return True
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    @property
    def vendee(self):
        return self.is_vendee

    @property
    def vendor(self):
        return self.is_vendor

    @property
    def dispatcher(self):
        return self.is_dispatcher

    def check_active(self):
        if self.is_active:
            return "Your account is Active!"
        else:
            return "Your account is not Activated!"


class Vendor(models.Model):
    user = models.OneToOneField(WebUser, on_delete=models.CASCADE, primary_key=True)
    business_name = models.CharField(max_length=256)
    business_type = models.CharField(max_length=32, choices=MallTypeKind.CHOICES, default='SUPERMARKET')

    class Meta:
        verbose_name_plural = 'Vendors'

    def __str__(self):
        if self.user.email:
            return self.user.email
        return self.business_name

    def get_absolute_url(self):
        kwargs = {"pk": self.pk}
        return reverse("vendors:vendor-detail", kwargs=kwargs)

    # def generate_slug(self):
    #     max_length = 256
    #     value = self.business_name
    #     slug_candidate = slug_original = slugify(value, allow_unicode=True)[:max_length]
    #     for i in itertools.count(1):
    #         if not Vendor.objects.filter(slug=slug_candidate).exists():
    #             break
    #         id_length = len(str(i)) + 1
    #         new_slug_text_part_length = len(slug_original) - id_length
    #         original_slug_with_id_length = len(slug_original) + id_length
    #
    #         candidate_slug_part = slug_original[
    #                               :new_slug_text_part_length] if original_slug_with_id_length > max_length else slug_original
    #         slug_candidate = "{}-{}".format(candidate_slug_part, i)
    #
    #     self.slug = slug_candidate
    #
    # def slug_length(self):
    #     return len(self.slug)
    #
    # def get_absolute_url(self):
    #     return reverse("vendors:vendor-detail", args=[str(self.slug)])
    #
    # def save(self, *args, **kwargs):
    #     if not self.pk:
    #         self.generate_slug()
    #
    #     super().save(*args, **kwargs)
    #
    #     pass


class Vendee(models.Model):
    user = models.OneToOneField(WebUser, on_delete=models.CASCADE, primary_key=True)
    default_shipping_address = models.ForeignKey(
        Address, related_name="+", null=True, blank=True, on_delete=models.SET_NULL)
    default_billing_address = models.ForeignKey(
        Address, related_name="+", null=True, blank=True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name_plural = 'Vendee'

    def __str__(self):
        if self.user.email:
            return self.user.email
        return self.user.first_name

    pass

vendors/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth import get_user_model
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm, \
    AuthenticationForm
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMultiAlternatives
from django.db import transaction
from django.template import loader
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode

from accounts.models import Vendor, Vendee, Address
from ahia.settings import DEFAULT_FROM_EMAIL, SUPPORT_FROM_EMAIL
from malls import MallTypeKind

User = get_user_model()


# Account authentication forms

# Form for loging in users

class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput)
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['password'].widget.attrs.update({'class': 'form-control'})


class VendorSignUpForm(UserCreationForm):
    business_name = forms.CharField(widget=forms.TextInput(attrs=({'class': 'form-control'})))
    business_type = forms.ChoiceField(choices=MallTypeKind.CHOICES)

    # slug = forms.SlugField(widget=forms.HiddenInput())

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('email', 'first_name', 'last_name', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(VendorSignUpForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['first_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['password1'].widget.attrs.update({'class': 'form-control'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control'})
        self.fields['business_type'].widget.attrs.update({'class': 'form-control'})

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_vendor = True
        user.save()
        vendor = Vendor.objects.create(user=user)
        return user

    def send_mail(self):
        subject = render_to_string("emails/vendor/vendor_welcome_subject.txt").strip()
        text_body = render_to_string("emails/vendor/vendor_welcome_email.txt")
        html_body = render_to_string("emails/vendor/vendor_welcome_email.html")
        from_email = DEFAULT_FROM_EMAIL
        to_email = self.cleaned_data['email']
        email_message = EmailMultiAlternatives(subject=subject, body=html_body,
                                               from_email=from_email, to=[to_email])
        email_message.attach_alternative(html_body, "text/html")
        email_message.send()


class VendeeSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('email', 'first_name', 'last_name', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(VendeeSignUpForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['first_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['password1'].widget.attrs.update({'class': 'form-control'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control'})

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_vendee = True
        user.save()
        vendee = Vendee.objects.create(user=user)
        return user

    def send_email(self):
        email_subject = render_to_string("emails/vendee/vendee_welcome_subject.txt").strip()
        text_body = render_to_string("emails/vendee/vendee_welcome_email.txt")
        html_body = render_to_string("emails/vendee/vendee_welcome_email.html")
        sender_email = DEFAULT_FROM_EMAIL
        recipients_email = self.cleaned_data['email']
        email_message = EmailMultiAlternatives(subject=email_subject, body=html_body,
                                               from_email=sender_email, to=[recipients_email])
        email_message.attach_alternative(html_body, "text/html")
        email_message.send()


class ResetPasswordForm(PasswordResetForm):

    def send_mail(
            self,
            subject_template_name,
            email_template_name,
            context,
            from_email,
            to_email,
            html_email_template_name=None,
    ):
        """
        Send a django.core.mail.EmailMultiAlternatives to `to_email`.
        """
        subject = loader.render_to_string(subject_template_name, context)
        # Email subject *must not* contain newlines
        subject = "".join(subject.splitlines())
        body = render_to_string(email_template_name, context)
        from_email = SUPPORT_FROM_EMAIL

        email_message = EmailMultiAlternatives(subject, body, from_email, [to_email])
        email_message.attach_alternative(body, "text/html")

        email_message.send()


class CreateAddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = '__all__'

vendors/forms.py
import datetime

from django import forms
from django.contrib.auth import get_user_model

from accounts.models import Vendor, Address

User = get_user_model()


class WebUserUpdateForm(forms.ModelForm):
    birth_date = forms.DateField(initial=datetime.date.today)

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'avatar', 'birth_date', 'gender',)

    def __init__(self, *args, **kwargs):
        super(WebUserUpdateForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['first_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['avatar'].widget.attrs.update({'class': 'form-control'})
        self.fields['gender'].widget.attrs.update({'class': 'form-control'})
        self.fields['birth_date'].widget.attrs.update({'class': 'form-control vDateField datepicker-input'})


class VendorUpdateForm(forms.ModelForm):
    class Meta:
        model = Vendor
        fields = ('business_name', 'business_type',)

    def __init__(self, *args, **kwargs):
        super(VendorUpdateForm, self).__init__(*args, **kwargs)
        self.fields['business_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['business_type'].widget.attrs.update({'class': 'form-control'})

vendors/templates/vendors/vendor-edit-profile.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Vendor Profile {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block nav_style %} navbar-light navbar-transparent navbar-theme-secondary {% endblock nav_style %}

{% block content %}

    <div class="section section-lg pt-5 pt-md-7 bg-gray-200">
        <div class="container">
            <div class="row pt-5 pt-md-0">

                {% include 'includes/messages.html' %}

                {% include 'includes/vendorMenu.html' %}


                <div class="col-12 col-lg-8">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card card-body bg-white border-gray-300 mb-4">
                                <h2 class="h5 mb-4">Personal Information</h2>
                                <form method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="row">

                                        <div class="col-md-6 mb-3">
                                            <div class="mb-3">
                                                <label for="id_first_name">First Name</label>
                                                {{ web_user_form.first_name }}
                                            </div>
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <div class="mb-3">
                                                <label for="id_last_name">Last Name</label>
                                                {{ web_user_form.last_name }}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row align-items-center">
                                        <div class="col-md-6 mb-3">
                                            <div class="mb-3">
                                                <label for="id_birth_date">Birthday</label>
                                                {{ web_user_form.birth_date }}
                                            </div>
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <label for="id_gender">Gender</label>
                                            {{ web_user_form.gender }}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6 mb-3">
                                            <div class="mb-3">
                                                <label for="id_email">Email</label>
                                                {{ web_user_form.email }}
                                            </div>
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <div class="mb-3">
                                                <label for="id_avatar">Avatar</label>
                                                {{ web_user_form.avatar }}
                                            </div>
                                        </div>
                                    </div>
                                    <h2 class="h5 my-4">Business Information</h2>
                                    <div class="row">
                                        <div class="col-md-6 mb-3">
                                            <div class="mb-3">
                                                <label for="id_business_name">Business Name</label>
                                                {{ vendor_form.business_name }}
                                            </div>
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <div class="mb-3">
                                                <label for="id_business_type">Business Type</label>
                                                {{ vendor_form.business_type }}
                                            </div>
                                        </div>
                                    </div>

                                    <div class="mt-2">
                                        <button type="submit" class="btn btn-primary">UPDATE PROFILE DETAILS</button>
                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

vendors/templates/vendors/vendor-home.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Vendor Account {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block nav_style %} navbar-light navbar-transparent navbar-theme-secondary {% endblock nav_style %}

{% block content %}

    <div class="section section-lg pt-5 pt-md-7 bg-gray-200">
        <div class="container">
            <div class="row pt-5 pt-md-0">
                {% include 'includes/messages.html' %}

                 {% include 'includes/vendorMenu.html' %}

                <div class="col-12 col-lg-8">
                    <div class="row">
                        <div class="col-12 col-sm-6 mb-4">
                            <div class="card border-gray-300">
                                <div class="card-body d-block d-md-flex align-items-center">
                                    <div class="icon icon-shape icon-md icon-shape-primary rounded-circle me-3 mb-4 mb-md-0">
                                        <span class="fas fa-wallet"></span></div>
                                    <div>
                                    <span class="d-block h6 fw-normal">
                                        Global Budget
                                    </span>
                                        <h5 class="h3 fw-bold mb-1">$25,370.00</h5>
                                        <div class="small mt-2">
                                            <span class="fas fa-angle-up text-success"></span>
                                            <span class="text-success fw-bold">18.2%</span> higher vs previous month
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-sm-6 mb-4">
                            <div class="card border-gray-300">
                                <div class="card-body d-block d-md-flex align-items-center">
                                    <div class="icon icon-shape icon-md icon-shape-primary rounded-circle me-3 mb-4 mb-md-0">
                                        <span class="fas fa-file-invoice-dollar"></span></div>
                                    <div>
                                        <span class="d-block h6 fw-normal">
                                            Sales
                                        </span>
                                        <h5 class="h3 fw-bold mb-1">$5,220.00</h5>
                                        <div class="small mt-2">
                                            <span class="fas fa-angle-up text-success"></span>
                                            <span class="text-success fw-bold">4.2%</span> higher vs previous month
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-md-6 mb-4">
                            <div class="card border-gray-300">
                                <div class="card-body d-flex flex-row align-items-center flex-0 border-bottom">
                                    <div class="d-block">
                                        <div class="h6 fw-normal text-gray mb-2">New customers</div>
                                        <h2 class="h3">452</h2>
                                        <div class="small mt-2">
                                            <span class="fas fa-angle-up text-success"></span>
                                            <span class="text-success fw-bold">18.2%</span>
                                        </div>
                                    </div>
                                    <div class="d-block ms-auto">
                                        <div class="d-flex align-items-center text-right mb-2">
                                            <span class="shape-xs rounded-circle bg-dark me-2"></span>
                                            <span class="fw-normal small">Last month</span>
                                        </div>
                                        <div class="d-flex align-items-center text-right">
                                            <span class="shape-xs rounded-circle bg-tertiary me-2"></span>
                                            <span class="fw-normal small">This month</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-body p-2">
                                    <div class="ct-chart-5 ct-golden-section ct-series-e"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-md-6 mb-4">
                            <div class="card border-gray-300">
                                <div class="card-body d-flex flex-row align-items-center flex-0 border-bottom">
                                    <div class="d-block">
                                        <div class="h6 fw-normal text-gray mb-2">Revenues</div>
                                        <h2 class="h3">10,567</h2>
                                        <div class="small mt-2">
                                            <span class="fas fa-angle-up text-success"></span>
                                            <span class="text-success fw-bold">$10.57%</span>
                                        </div>
                                    </div>
                                    <div class="d-block ms-auto">
                                        <div class="d-flex align-items-center text-right mb-2">
                                            <span class="shape-xs rounded-circle bg-dark me-2"></span>
                                            <span class="fw-normal small">Real Estate</span>
                                        </div>
                                        <div class="d-flex align-items-center text-right mb-2">
                                            <span class="shape-xs rounded-circle bg-tertiary me-2"></span>
                                            <span class="fw-normal small">Electronic</span>
                                        </div>
                                        <div class="d-flex align-items-center text-right mb-2">
                                            <span class="shape-xs rounded-circle bg-primary me-2"></span>
                                            <span class="fw-normal small">Clothes</span>
                                        </div>
                                        <div class="d-flex align-items-center text-right">
                                            <span class="shape-xs rounded-circle bg-success me-2"></span>
                                            <span class="fw-normal small">Auto</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-body p-2">
                                    <div class="ct-chart-7 ct-golden-section ct-series-e"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 mb-4">
                            <div class="card border-gray-300">
                                <div class="card-body d-flex flex-row align-items-center flex-0 border-bottom">
                                    <div class="d-block">
                                        <div class="h6 fw-normal text-gray mb-2">Sales Value</div>
                                        <h2 class="h3">10,567</h2>
                                        <div class="small mt-2">
                                            <span class="fas fa-angle-up text-success"></span>
                                            <span class="text-success fw-bold">$10.57%</span>
                                        </div>
                                    </div>
                                    <div class="d-flex ms-auto">
                                        <a href="#" class="btn btn-tertiary btn-sm me-3">Month</a>
                                        <a href="#" class="btn btn-white border-gray-300 btn-sm me-3">Week</a>
                                    </div>
                                </div>
                                <div class="card-body p-2">
                                    <div class="ct-chart-8 ct-major-tenth ct-series-b"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}